arch = "AArch64"
name = "CoFF"
hash = "c498893326a72e90ca344d2e024e129e"
symbolic = []

[[self_modify]]
address = "f:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X1 = "f:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
"""

[thread.1]
init = {  }
code = """
	BL f
	MOV W0,W10
	BL f
	MOV W1,W10
	B Lout
f:
	B l0
l1:
	MOV W10,#2
	RET
l0:
	MOV W10,#1
	RET
Lout:
"""

[final]
expect = "sat"
assertion = "1:X0 = 2 & 1:X1 = 1"
