arch = "AArch64"
name = "CoFF-isb"
hash = "b31b140c63bc1c9606272b3cbb37a827"
symbolic = []

[[self_modify]]
address = "L1:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X1 = "L1:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
"""

[thread.1]
init = {  }
code = """
	BL L1
	MOV X8,X9
	ISB
	BL L1
	B Lout
L1:
	B Lfail
	MOV X9,#1
	RET
Lfail:
	MOV X9,#0
	RET
Lout:
"""

[final]
expect = "sat"
assertion = "1:X8 = 1 & 1:X9 = 0"
