arch = "AArch64"
name = "ISA2.F+dc+ic+ctrl-isb"
hash = "8d8448026f2fa2f9b3173851a551d482"
symbolic = ["x", "y"]

[[self_modify]]
address = "L1:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X3 = "x", X2 = "1", X1 = "f:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
	DC CVAU,X1
	DSB ISH
	STR W2,[X3]
"""

[thread.1]
init = { X3 = "y", X2 = "1", X4 = "f:", X1 = "x" }
code = """
	LDR W0,[X1]
	DSB ISH
	IC IVAU,X4
	DSB ISH
	STR W2,[X3]
"""

[thread.2]
init = { X2 = "y" }
code = """
	LDR W0,[X2]
	CBNZ W0,l
l:
	ISB
	BL f
	MOV W1,W10
	B Lout
f:
	B l0
l1:
	MOV W10,#2
	RET
l0:
	MOV W10,#1
	RET
Lout:
"""

[final]
expect = "unsat"
assertion = "1:X0 = 1 & 2:X0 = 1 & 2:X1 = 1"
