arch = "AArch64"
name = "MP.FR+dmb+fpo-fe"
hash = "90e5403245b81607717f906d195713ac"
symbolic = ["x"]

[[self_modify]]
address = "f:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X3 = "f:", X2 = "0x14000001", X1 = "x", X0 = "1" }
code = """
	STR W0,[X1]
	DMB SY
	STR W2,[X3]
"""

[thread.1]
init = { X2 = "x" }
code = """
	BL f
	MOV W0,W10
	LDR W1,[X2]
	B Lout
f:
	B l0
l1:
	MOV W10,#2
	RET
l0:
	MOV W10,#1
	RET
Lout:
"""

[final]
expect = "unsat"
assertion = "1:X0 = 2 & 1:X1 = 0"
