arch = "AArch64"
name = "MP.FF+cachesyncstrong+fpo"
hash = "8048ac9cd62ca1813270ac5d415d3c2e"
generator = "diyone7 (version 7.52+10(dev))"
com = "Iff Fif"
orig = "CacheSyncStrongdWW Iffe PodRR Fife"
symbolic = []

[[self_modify]]
address = "Lself01:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[[self_modify]]
address = "Lself00:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X2 = "Lself01:", X1 = "Lself00:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
	DC CIVAC,X1
	DSB ISH
	IC IVAU,X1
	DSB ISH
	STR W0,[X2]
"""

[thread.1]
init = {  }
code = """
Lself01:
	B L00
	MOV W0,#2
	B L01
L00:
	MOV W0,#1
L01:
Lself00:
	B L02
	MOV W1,#2
	B L03
L02:
	MOV W1,#1
L03:
"""

[final]
expect = "sat"
assertion = "1:X0 = 2 & 1:X1 = 1"
