arch = "AArch64"
name = "MP.RF+dmb+ctrl-isb"
hash = "3a44aa0c351c8517e88199525fe2ae2f"
symbolic = ["x"]

[[self_modify]]
address = "f:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X3 = "x", X2 = "1", X1 = "f:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
	DMB SY
	STR W2,[X3]
"""

[thread.1]
init = { X2 = "x" }
code = """
	LDR W0,[X2]
	CBNZ W0,l
l:
	ISB
	BL f
	MOV W1,W10
	B Lout
f:
	B l0
l1:
	MOV W10,#2
	RET
l0:
	MOV W10,#1
	RET
Lout:
"""

[final]
expect = "sat"
assertion = "1:X0 = 1 & 1:X1 = 1"
