arch = "AArch64"
name = "MP.RRF+dmb+addr-cachesync-isb"
hash = "adc413ef44349b708aeb4fa26586cc36"
symbolic = ["x", "z"]

[[self_modify]]
address = "L4:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[locations]
"x" = "0"
"z" = "0"

[types]
"x" = "uint64_t"
"z" = "uint64_t"

[thread.0]
init = { X3 = "x", X1 = "L4:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
	DMB SY
	MOV X2,#1
	STR X2,[X3]
"""

[thread.1]
init = { X5 = "L4:", X4 = "z", X1 = "x" }
code = """
	LDR X0,[X1]
	EOR X2,X0,X0
	LDR X3,[X4,X2]
	DC CVAU, X5
	DSB ISH
	IC IVAU, X5
	DSB ISH
	ISB
L4:
	B fail_L4
	MOV X6,#1
	B Lout
fail_L4:
	MOV X6,#0
	B Lout
Lout:
"""

[final]
expect = "unsat"
assertion = "1:X0 = 1 & 1:X3 = 0 & 1:X6 = 0"
