arch = "AArch64"
name = "SM+cachesync-isb"
hash = "350f504d9d3a245993208f985f77a9f6"
symbolic = []

[[self_modify]]
address = "f:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X1 = "f:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
	DC CVAU,X1
	DSB ISH
	IC IVAU,X1
	DSB ISH
	ISB
	BL f
	MOV W2,W10
	B Lout
f:
	B l0
l1:
	MOV W10,#2
	RET
l0:
	MOV W10,#1
	RET
Lout:
"""

[final]
expect = "unsat"
assertion = "0:X2 = 0"
