arch = "AArch64"
name = "SM+cachesync"
hash = "099225645d57704eabd3f700b06dfa90"
symbolic = []

[[self_modify]]
address = "L1:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X1 = "L1:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
	DC CVAU,X1
	DSB ISH
	IC IVAU,X1
	DSB ISH
	NOP
L1:
	B Lfail
	MOV X9,#1
	B Lout
Lfail:
	MOV X9,#0
Lout:
"""

[final]
expect = "sat"
assertion = "0:X9 = 0"
