arch = "AArch64"
name = "SM+dc-dmb-ctrl-isb"
hash = "30b683165f5efdcbc79a0a933a461fbd"
symbolic = []

[[self_modify]]
address = "L1:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X1 = "L1:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
	DC CVAU,X1
	DMB SY
	CBZ W0,LC00
LC00:
	ISB
L1:
	B Lfail
	MOV X9,#1
	B Lout
Lfail:
	MOV X9,#0
Lout:
"""

[final]
expect = "sat"
assertion = "0:X9 = 0"
