arch = "AArch64"
name = "WRC.F.RF"
hash = "e8060979246547ed683546dc113b5c16"
stable = "X9"
symbolic = ["x"]

[[self_modify]]
address = "L2:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[locations]
"x" = "0"

[types]
"x" = "uint64_t"

[thread.0]
init = { X1 = "L2:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
"""

[thread.1]
init = { X2 = "x" }
code = """
	BL L2
	B Lover
L2:
	B Lfail_L2
	MOV X9, #1
	RET
Lfail_L2:
	MOV X9, #0
	RET
Lover:
	MOV X1, #1
	STR X1, [X2]
Lend:
"""

[thread.2]
init = { X3 = "L2:", X2 = "x" }
code = """
	LDR X1, [X2]
	BLR X3
"""

[final]
expect = "sat"
assertion = "1:X9 = 1 & 2:X1 = 1 & 2:X9 = 0"
